// Code generated by Fern. DO NOT EDIT.

package ordertransaction

import (
	context "context"
	io "io"

	junctiongo "github.com/junction-api/junction-go"
	core "github.com/junction-api/junction-go/core"
	internal "github.com/junction-api/junction-go/internal"
	option "github.com/junction-api/junction-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) GetTransaction(
	ctx context.Context,
	request *junctiongo.GetTransactionOrderTransactionRequest,
	opts ...option.RequestOption,
) (*junctiongo.GetOrderTransactionResponse, error) {
	response, err := c.WithRawResponse.GetTransaction(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetTransactionResult(
	ctx context.Context,
	request *junctiongo.GetTransactionResultOrderTransactionRequest,
	opts ...option.RequestOption,
) (*junctiongo.LabResultsRaw, error) {
	response, err := c.WithRawResponse.GetTransactionResult(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetTransactionResultPdf(
	ctx context.Context,
	request *junctiongo.GetTransactionResultPdfOrderTransactionRequest,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.GetTransactionResultPdf(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
