// Code generated by Fern. DO NOT EDIT.

package vitals

import (
	context "context"

	junctiongo "github.com/junction-api/junction-go"
	core "github.com/junction-api/junction-go/core"
	internal "github.com/junction-api/junction-go/internal"
	option "github.com/junction-api/junction-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) WorkoutSwimmingStrokeGrouped(
	ctx context.Context,
	request *junctiongo.WorkoutSwimmingStrokeGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedWorkoutSwimmingStrokeResponse, error) {
	response, err := c.WithRawResponse.WorkoutSwimmingStrokeGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) WorkoutDistanceGrouped(
	ctx context.Context,
	request *junctiongo.WorkoutDistanceGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedWorkoutDistanceResponse, error) {
	response, err := c.WithRawResponse.WorkoutDistanceGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) HeartRateRecoveryOneMinuteGrouped(
	ctx context.Context,
	request *junctiongo.HeartRateRecoveryOneMinuteGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedHeartRateRecoveryOneMinuteResponse, error) {
	response, err := c.WithRawResponse.HeartRateRecoveryOneMinuteGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) WaistCircumferenceGrouped(
	ctx context.Context,
	request *junctiongo.WaistCircumferenceGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedWaistCircumferenceResponse, error) {
	response, err := c.WithRawResponse.WaistCircumferenceGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) LeanBodyMassGrouped(
	ctx context.Context,
	request *junctiongo.LeanBodyMassGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedLeanBodyMassResponse, error) {
	response, err := c.WithRawResponse.LeanBodyMassGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) BodyMassIndexGrouped(
	ctx context.Context,
	request *junctiongo.BodyMassIndexGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedBodyMassIndexResponse, error) {
	response, err := c.WithRawResponse.BodyMassIndexGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) BasalBodyTemperatureGrouped(
	ctx context.Context,
	request *junctiongo.BasalBodyTemperatureGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedBasalBodyTemperatureResponse, error) {
	response, err := c.WithRawResponse.BasalBodyTemperatureGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) HandwashingGrouped(
	ctx context.Context,
	request *junctiongo.HandwashingGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedHandwashingResponse, error) {
	response, err := c.WithRawResponse.HandwashingGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DaylightExposureGrouped(
	ctx context.Context,
	request *junctiongo.DaylightExposureGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedDaylightExposureResponse, error) {
	response, err := c.WithRawResponse.DaylightExposureGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) UvExposureGrouped(
	ctx context.Context,
	request *junctiongo.UvExposureGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedUvExposureResponse, error) {
	response, err := c.WithRawResponse.UvExposureGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) FallGrouped(
	ctx context.Context,
	request *junctiongo.FallGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedFallResponse, error) {
	response, err := c.WithRawResponse.FallGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) InhalerUsageGrouped(
	ctx context.Context,
	request *junctiongo.InhalerUsageGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedInhalerUsageResponse, error) {
	response, err := c.WithRawResponse.InhalerUsageGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PeakExpiratoryFlowRateGrouped(
	ctx context.Context,
	request *junctiongo.PeakExpiratoryFlowRateGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedPeakExpiratoryFlowRateResponse, error) {
	response, err := c.WithRawResponse.PeakExpiratoryFlowRateGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ForcedVitalCapacityGrouped(
	ctx context.Context,
	request *junctiongo.ForcedVitalCapacityGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedForcedVitalCapacityResponse, error) {
	response, err := c.WithRawResponse.ForcedVitalCapacityGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ForcedExpiratoryVolume1Grouped(
	ctx context.Context,
	request *junctiongo.ForcedExpiratoryVolume1GroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedForcedExpiratoryVolume1Response, error) {
	response, err := c.WithRawResponse.ForcedExpiratoryVolume1Grouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) WheelchairPushGrouped(
	ctx context.Context,
	request *junctiongo.WheelchairPushGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedWheelchairPushResponse, error) {
	response, err := c.WithRawResponse.WheelchairPushGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) SleepBreathingDisturbanceGrouped(
	ctx context.Context,
	request *junctiongo.SleepBreathingDisturbanceGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedSleepBreathingDisturbanceResponse, error) {
	response, err := c.WithRawResponse.SleepBreathingDisturbanceGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) SleepApneaAlertGrouped(
	ctx context.Context,
	request *junctiongo.SleepApneaAlertGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedSleepApneaAlertResponse, error) {
	response, err := c.WithRawResponse.SleepApneaAlertGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StandDurationGrouped(
	ctx context.Context,
	request *junctiongo.StandDurationGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedStandDurationResponse, error) {
	response, err := c.WithRawResponse.StandDurationGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StandHourGrouped(
	ctx context.Context,
	request *junctiongo.StandHourGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedStandHourResponse, error) {
	response, err := c.WithRawResponse.StandHourGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) HeartRateAlertGrouped(
	ctx context.Context,
	request *junctiongo.HeartRateAlertGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedHeartRateAlertResponse, error) {
	response, err := c.WithRawResponse.HeartRateAlertGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) AfibBurdenGrouped(
	ctx context.Context,
	request *junctiongo.AfibBurdenGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedAFibBurdenResponse, error) {
	response, err := c.WithRawResponse.AfibBurdenGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) WorkoutDurationGrouped(
	ctx context.Context,
	request *junctiongo.WorkoutDurationGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedWorkoutDurationResponse, error) {
	response, err := c.WithRawResponse.WorkoutDurationGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Vo2MaxGrouped(
	ctx context.Context,
	request *junctiongo.Vo2MaxGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedVo2MaxResponse, error) {
	response, err := c.WithRawResponse.Vo2MaxGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StressLevelGrouped(
	ctx context.Context,
	request *junctiongo.StressLevelGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedStressLevelResponse, error) {
	response, err := c.WithRawResponse.StressLevelGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) MindfulnessMinutesGrouped(
	ctx context.Context,
	request *junctiongo.MindfulnessMinutesGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedMindfulnessMinutesResponse, error) {
	response, err := c.WithRawResponse.MindfulnessMinutesGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CaffeineGrouped(
	ctx context.Context,
	request *junctiongo.CaffeineGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedCaffeineResponse, error) {
	response, err := c.WithRawResponse.CaffeineGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) WaterGrouped(
	ctx context.Context,
	request *junctiongo.WaterGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedWaterResponse, error) {
	response, err := c.WithRawResponse.WaterGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StepsGrouped(
	ctx context.Context,
	request *junctiongo.StepsGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedStepsResponse, error) {
	response, err := c.WithRawResponse.StepsGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) FloorsClimbedGrouped(
	ctx context.Context,
	request *junctiongo.FloorsClimbedGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedFloorsClimbedResponse, error) {
	response, err := c.WithRawResponse.FloorsClimbedGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DistanceGrouped(
	ctx context.Context,
	request *junctiongo.DistanceGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedDistanceResponse, error) {
	response, err := c.WithRawResponse.DistanceGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CaloriesBasalGrouped(
	ctx context.Context,
	request *junctiongo.CaloriesBasalGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedCaloriesBasalResponse, error) {
	response, err := c.WithRawResponse.CaloriesBasalGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CaloriesActiveGrouped(
	ctx context.Context,
	request *junctiongo.CaloriesActiveGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedCaloriesActiveResponse, error) {
	response, err := c.WithRawResponse.CaloriesActiveGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) RespiratoryRateGrouped(
	ctx context.Context,
	request *junctiongo.RespiratoryRateGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedRespiratoryRateResponse, error) {
	response, err := c.WithRawResponse.RespiratoryRateGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) NoteGrouped(
	ctx context.Context,
	request *junctiongo.NoteGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedNoteResponse, error) {
	response, err := c.WithRawResponse.NoteGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) InsulinInjectionGrouped(
	ctx context.Context,
	request *junctiongo.InsulinInjectionGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedInsulinInjectionResponse, error) {
	response, err := c.WithRawResponse.InsulinInjectionGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) IgeGrouped(
	ctx context.Context,
	request *junctiongo.IgeGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedIgeResponse, error) {
	response, err := c.WithRawResponse.IgeGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) IggGrouped(
	ctx context.Context,
	request *junctiongo.IggGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedIggResponse, error) {
	response, err := c.WithRawResponse.IggGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) HrvGrouped(
	ctx context.Context,
	request *junctiongo.HrvGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedHrvResponse, error) {
	response, err := c.WithRawResponse.HrvGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) HeartrateGrouped(
	ctx context.Context,
	request *junctiongo.HeartrateGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedHeartRateResponse, error) {
	response, err := c.WithRawResponse.HeartrateGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GlucoseGrouped(
	ctx context.Context,
	request *junctiongo.GlucoseGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedGlucoseResponse, error) {
	response, err := c.WithRawResponse.GlucoseGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CholesterolGrouped(
	ctx context.Context,
	request *junctiongo.CholesterolGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedCholesterolResponse, error) {
	response, err := c.WithRawResponse.CholesterolGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CarbohydratesGrouped(
	ctx context.Context,
	request *junctiongo.CarbohydratesGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedCarbohydratesResponse, error) {
	response, err := c.WithRawResponse.CarbohydratesGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) BodyTemperatureDeltaGrouped(
	ctx context.Context,
	request *junctiongo.BodyTemperatureDeltaGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedBodyTemperatureDeltaResponse, error) {
	response, err := c.WithRawResponse.BodyTemperatureDeltaGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) BodyTemperatureGrouped(
	ctx context.Context,
	request *junctiongo.BodyTemperatureGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedBodyTemperatureResponse, error) {
	response, err := c.WithRawResponse.BodyTemperatureGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) BodyWeightGrouped(
	ctx context.Context,
	request *junctiongo.BodyWeightGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedBodyWeightResponse, error) {
	response, err := c.WithRawResponse.BodyWeightGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) BodyFatGrouped(
	ctx context.Context,
	request *junctiongo.BodyFatGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedBodyFatResponse, error) {
	response, err := c.WithRawResponse.BodyFatGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) BloodOxygenGrouped(
	ctx context.Context,
	request *junctiongo.BloodOxygenGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedBloodOxygenResponse, error) {
	response, err := c.WithRawResponse.BloodOxygenGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ElectrocardiogramVoltageGrouped(
	ctx context.Context,
	request *junctiongo.ElectrocardiogramVoltageGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedElectrocardiogramVoltageResponse, error) {
	response, err := c.WithRawResponse.ElectrocardiogramVoltageGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) BloodPressureGrouped(
	ctx context.Context,
	request *junctiongo.BloodPressureGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*junctiongo.GroupedBloodPressureResponse, error) {
	response, err := c.WithRawResponse.BloodPressureGrouped(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
