// Code generated by Fern. DO NOT EDIT.

package vitals

import (
	context "context"
	http "net/http"

	junctiongo "github.com/junction-api/junction-go/v2"
	core "github.com/junction-api/junction-go/v2/core"
	internal "github.com/junction-api/junction-go/v2/internal"
	option "github.com/junction-api/junction-go/v2/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) WorkoutSwimmingStrokeGrouped(
	ctx context.Context,
	request *junctiongo.WorkoutSwimmingStrokeGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedWorkoutSwimmingStrokeResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/workout_swimming_stroke/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedWorkoutSwimmingStrokeResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedWorkoutSwimmingStrokeResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) WorkoutDistanceGrouped(
	ctx context.Context,
	request *junctiongo.WorkoutDistanceGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedWorkoutDistanceResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/workout_distance/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedWorkoutDistanceResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedWorkoutDistanceResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) HeartRateRecoveryOneMinuteGrouped(
	ctx context.Context,
	request *junctiongo.HeartRateRecoveryOneMinuteGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedHeartRateRecoveryOneMinuteResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/heart_rate_recovery_one_minute/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedHeartRateRecoveryOneMinuteResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedHeartRateRecoveryOneMinuteResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) WaistCircumferenceGrouped(
	ctx context.Context,
	request *junctiongo.WaistCircumferenceGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedWaistCircumferenceResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/waist_circumference/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedWaistCircumferenceResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedWaistCircumferenceResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) LeanBodyMassGrouped(
	ctx context.Context,
	request *junctiongo.LeanBodyMassGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedLeanBodyMassResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/lean_body_mass/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedLeanBodyMassResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedLeanBodyMassResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) BodyMassIndexGrouped(
	ctx context.Context,
	request *junctiongo.BodyMassIndexGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedBodyMassIndexResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/body_mass_index/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedBodyMassIndexResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedBodyMassIndexResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) BasalBodyTemperatureGrouped(
	ctx context.Context,
	request *junctiongo.BasalBodyTemperatureGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedBasalBodyTemperatureResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/basal_body_temperature/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedBasalBodyTemperatureResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedBasalBodyTemperatureResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) HandwashingGrouped(
	ctx context.Context,
	request *junctiongo.HandwashingGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedHandwashingResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/handwashing/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedHandwashingResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedHandwashingResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DaylightExposureGrouped(
	ctx context.Context,
	request *junctiongo.DaylightExposureGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedDaylightExposureResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/daylight_exposure/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedDaylightExposureResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedDaylightExposureResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UvExposureGrouped(
	ctx context.Context,
	request *junctiongo.UvExposureGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedUvExposureResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/uv_exposure/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedUvExposureResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedUvExposureResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) FallGrouped(
	ctx context.Context,
	request *junctiongo.FallGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedFallResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/fall/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedFallResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedFallResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) InhalerUsageGrouped(
	ctx context.Context,
	request *junctiongo.InhalerUsageGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedInhalerUsageResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/inhaler_usage/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedInhalerUsageResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedInhalerUsageResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PeakExpiratoryFlowRateGrouped(
	ctx context.Context,
	request *junctiongo.PeakExpiratoryFlowRateGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedPeakExpiratoryFlowRateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/peak_expiratory_flow_rate/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedPeakExpiratoryFlowRateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedPeakExpiratoryFlowRateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ForcedVitalCapacityGrouped(
	ctx context.Context,
	request *junctiongo.ForcedVitalCapacityGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedForcedVitalCapacityResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/forced_vital_capacity/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedForcedVitalCapacityResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedForcedVitalCapacityResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ForcedExpiratoryVolume1Grouped(
	ctx context.Context,
	request *junctiongo.ForcedExpiratoryVolume1GroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedForcedExpiratoryVolume1Response], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/forced_expiratory_volume_1/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedForcedExpiratoryVolume1Response
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedForcedExpiratoryVolume1Response]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) WheelchairPushGrouped(
	ctx context.Context,
	request *junctiongo.WheelchairPushGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedWheelchairPushResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/wheelchair_push/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedWheelchairPushResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedWheelchairPushResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) SleepBreathingDisturbanceGrouped(
	ctx context.Context,
	request *junctiongo.SleepBreathingDisturbanceGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedSleepBreathingDisturbanceResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/sleep_breathing_disturbance/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedSleepBreathingDisturbanceResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedSleepBreathingDisturbanceResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) SleepApneaAlertGrouped(
	ctx context.Context,
	request *junctiongo.SleepApneaAlertGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedSleepApneaAlertResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/sleep_apnea_alert/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedSleepApneaAlertResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedSleepApneaAlertResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) StandDurationGrouped(
	ctx context.Context,
	request *junctiongo.StandDurationGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedStandDurationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/stand_duration/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedStandDurationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedStandDurationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) StandHourGrouped(
	ctx context.Context,
	request *junctiongo.StandHourGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedStandHourResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/stand_hour/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedStandHourResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedStandHourResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) HeartRateAlertGrouped(
	ctx context.Context,
	request *junctiongo.HeartRateAlertGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedHeartRateAlertResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/heart_rate_alert/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedHeartRateAlertResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedHeartRateAlertResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) AfibBurdenGrouped(
	ctx context.Context,
	request *junctiongo.AfibBurdenGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedAFibBurdenResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/afib_burden/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedAFibBurdenResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedAFibBurdenResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) WorkoutDurationGrouped(
	ctx context.Context,
	request *junctiongo.WorkoutDurationGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedWorkoutDurationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/workout_duration/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedWorkoutDurationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedWorkoutDurationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Vo2MaxGrouped(
	ctx context.Context,
	request *junctiongo.Vo2MaxGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedVo2MaxResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/vo2_max/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedVo2MaxResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedVo2MaxResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) StressLevelGrouped(
	ctx context.Context,
	request *junctiongo.StressLevelGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedStressLevelResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/stress_level/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedStressLevelResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedStressLevelResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) MindfulnessMinutesGrouped(
	ctx context.Context,
	request *junctiongo.MindfulnessMinutesGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedMindfulnessMinutesResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/mindfulness_minutes/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedMindfulnessMinutesResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedMindfulnessMinutesResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CaffeineGrouped(
	ctx context.Context,
	request *junctiongo.CaffeineGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedCaffeineResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/caffeine/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedCaffeineResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedCaffeineResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) WaterGrouped(
	ctx context.Context,
	request *junctiongo.WaterGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedWaterResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/water/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedWaterResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedWaterResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) StepsGrouped(
	ctx context.Context,
	request *junctiongo.StepsGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedStepsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/steps/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedStepsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedStepsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) FloorsClimbedGrouped(
	ctx context.Context,
	request *junctiongo.FloorsClimbedGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedFloorsClimbedResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/floors_climbed/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedFloorsClimbedResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedFloorsClimbedResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DistanceGrouped(
	ctx context.Context,
	request *junctiongo.DistanceGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedDistanceResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/distance/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedDistanceResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedDistanceResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CaloriesBasalGrouped(
	ctx context.Context,
	request *junctiongo.CaloriesBasalGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedCaloriesBasalResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/calories_basal/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedCaloriesBasalResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedCaloriesBasalResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CaloriesActiveGrouped(
	ctx context.Context,
	request *junctiongo.CaloriesActiveGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedCaloriesActiveResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/calories_active/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedCaloriesActiveResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedCaloriesActiveResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) RespiratoryRateGrouped(
	ctx context.Context,
	request *junctiongo.RespiratoryRateGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedRespiratoryRateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/respiratory_rate/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedRespiratoryRateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedRespiratoryRateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) NoteGrouped(
	ctx context.Context,
	request *junctiongo.NoteGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedNoteResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/note/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedNoteResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedNoteResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) InsulinInjectionGrouped(
	ctx context.Context,
	request *junctiongo.InsulinInjectionGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedInsulinInjectionResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/insulin_injection/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedInsulinInjectionResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedInsulinInjectionResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) IgeGrouped(
	ctx context.Context,
	request *junctiongo.IgeGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedIgeResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/ige/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedIgeResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedIgeResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) IggGrouped(
	ctx context.Context,
	request *junctiongo.IggGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedIggResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/igg/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedIggResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedIggResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) HrvGrouped(
	ctx context.Context,
	request *junctiongo.HrvGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedHrvResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/hrv/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedHrvResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedHrvResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) HeartrateGrouped(
	ctx context.Context,
	request *junctiongo.HeartrateGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedHeartRateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/heartrate/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedHeartRateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedHeartRateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GlucoseGrouped(
	ctx context.Context,
	request *junctiongo.GlucoseGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedGlucoseResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/glucose/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedGlucoseResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedGlucoseResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CholesterolGrouped(
	ctx context.Context,
	request *junctiongo.CholesterolGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedCholesterolResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/cholesterol/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedCholesterolResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedCholesterolResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CarbohydratesGrouped(
	ctx context.Context,
	request *junctiongo.CarbohydratesGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedCarbohydratesResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/carbohydrates/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedCarbohydratesResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedCarbohydratesResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) BodyTemperatureDeltaGrouped(
	ctx context.Context,
	request *junctiongo.BodyTemperatureDeltaGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedBodyTemperatureDeltaResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/body_temperature_delta/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedBodyTemperatureDeltaResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedBodyTemperatureDeltaResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) BodyTemperatureGrouped(
	ctx context.Context,
	request *junctiongo.BodyTemperatureGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedBodyTemperatureResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/body_temperature/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedBodyTemperatureResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedBodyTemperatureResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) BodyWeightGrouped(
	ctx context.Context,
	request *junctiongo.BodyWeightGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedBodyWeightResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/body_weight/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedBodyWeightResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedBodyWeightResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) BodyFatGrouped(
	ctx context.Context,
	request *junctiongo.BodyFatGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedBodyFatResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/body_fat/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedBodyFatResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedBodyFatResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) BloodOxygenGrouped(
	ctx context.Context,
	request *junctiongo.BloodOxygenGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedBloodOxygenResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/blood_oxygen/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedBloodOxygenResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedBloodOxygenResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ElectrocardiogramVoltageGrouped(
	ctx context.Context,
	request *junctiongo.ElectrocardiogramVoltageGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedElectrocardiogramVoltageResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/electrocardiogram_voltage/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedElectrocardiogramVoltageResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedElectrocardiogramVoltageResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) BloodPressureGrouped(
	ctx context.Context,
	request *junctiongo.BloodPressureGroupedVitalsRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.GroupedBloodPressureResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/timeseries/%v/blood_pressure/grouped",
		request.UserId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.GroupedBloodPressureResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.GroupedBloodPressureResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
