// Code generated by Fern. DO NOT EDIT.

package introspect

import (
	context "context"
	http "net/http"

	junctiongo "github.com/junction-api/junction-go"
	core "github.com/junction-api/junction-go/core"
	internal "github.com/junction-api/junction-go/internal"
	option "github.com/junction-api/junction-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) GetUserResources(
	ctx context.Context,
	request *junctiongo.GetUserResourcesIntrospectRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.UserResourcesResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := baseURL + "/v2/introspect/resources"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.UserResourcesResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.UserResourcesResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetUserHistoricalPulls(
	ctx context.Context,
	request *junctiongo.GetUserHistoricalPullsIntrospectRequest,
	opts ...option.RequestOption,
) (*core.Response[*junctiongo.UserHistoricalPullsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.us.junction.com",
	)
	endpointURL := baseURL + "/v2/introspect/historical_pull"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *junctiongo.UserHistoricalPullsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(junctiongo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*junctiongo.UserHistoricalPullsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
