// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersConfirmCheckoutSessionCheckoutRequest(t *testing.T) {
	t.Run("SetCheckoutSessionId", func(t *testing.T) {
		obj := &ConfirmCheckoutSessionCheckoutRequest{}
		var fernTestValueCheckoutSessionId string
		obj.SetCheckoutSessionId(fernTestValueCheckoutSessionId)
		assert.Equal(t, fernTestValueCheckoutSessionId, obj.CheckoutSessionId)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitConfirmCheckoutSessionCheckoutRequest(t *testing.T) {
	t.Run("SetCheckoutSessionId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConfirmCheckoutSessionCheckoutRequest{}
		var fernTestValueCheckoutSessionId string

		// Act
		obj.SetCheckoutSessionId(fernTestValueCheckoutSessionId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreateCheckoutQuoteBody(t *testing.T) {
	t.Run("SetOrderSet", func(t *testing.T) {
		obj := &CreateCheckoutQuoteBody{}
		var fernTestValueOrderSet *OrderSetRequest
		obj.SetOrderSet(fernTestValueOrderSet)
		assert.Equal(t, fernTestValueOrderSet, obj.OrderSet)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetModality", func(t *testing.T) {
		obj := &CreateCheckoutQuoteBody{}
		var fernTestValueModality LabTestCollectionMethod
		obj.SetModality(fernTestValueModality)
		assert.Equal(t, fernTestValueModality, obj.Modality)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPriority", func(t *testing.T) {
		obj := &CreateCheckoutQuoteBody{}
		var fernTestValuePriority bool
		obj.SetPriority(fernTestValuePriority)
		assert.Equal(t, fernTestValuePriority, obj.Priority)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUsState", func(t *testing.T) {
		obj := &CreateCheckoutQuoteBody{}
		var fernTestValueUsState string
		obj.SetUsState(fernTestValueUsState)
		assert.Equal(t, fernTestValueUsState, obj.UsState)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateCheckoutQuoteBody(t *testing.T) {
	t.Run("SetOrderSet_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateCheckoutQuoteBody{}
		var fernTestValueOrderSet *OrderSetRequest

		// Act
		obj.SetOrderSet(fernTestValueOrderSet)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetModality_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateCheckoutQuoteBody{}
		var fernTestValueModality LabTestCollectionMethod

		// Act
		obj.SetModality(fernTestValueModality)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPriority_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateCheckoutQuoteBody{}
		var fernTestValuePriority bool

		// Act
		obj.SetPriority(fernTestValuePriority)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUsState_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateCheckoutQuoteBody{}
		var fernTestValueUsState string

		// Act
		obj.SetUsState(fernTestValueUsState)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetCheckoutSessionCheckoutRequest(t *testing.T) {
	t.Run("SetCheckoutSessionId", func(t *testing.T) {
		obj := &GetCheckoutSessionCheckoutRequest{}
		var fernTestValueCheckoutSessionId string
		obj.SetCheckoutSessionId(fernTestValueCheckoutSessionId)
		assert.Equal(t, fernTestValueCheckoutSessionId, obj.CheckoutSessionId)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetCheckoutSessionCheckoutRequest(t *testing.T) {
	t.Run("SetCheckoutSessionId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetCheckoutSessionCheckoutRequest{}
		var fernTestValueCheckoutSessionId string

		// Act
		obj.SetCheckoutSessionId(fernTestValueCheckoutSessionId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetQuoteCheckoutRequest(t *testing.T) {
	t.Run("SetQuoteId", func(t *testing.T) {
		obj := &GetQuoteCheckoutRequest{}
		var fernTestValueQuoteId string
		obj.SetQuoteId(fernTestValueQuoteId)
		assert.Equal(t, fernTestValueQuoteId, obj.QuoteId)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetQuoteCheckoutRequest(t *testing.T) {
	t.Run("SetQuoteId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetQuoteCheckoutRequest{}
		var fernTestValueQuoteId string

		// Act
		obj.SetQuoteId(fernTestValueQuoteId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRefineCheckoutQuoteBody(t *testing.T) {
	t.Run("SetQuoteId", func(t *testing.T) {
		obj := &RefineCheckoutQuoteBody{}
		var fernTestValueQuoteId string
		obj.SetQuoteId(fernTestValueQuoteId)
		assert.Equal(t, fernTestValueQuoteId, obj.QuoteId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPriority", func(t *testing.T) {
		obj := &RefineCheckoutQuoteBody{}
		var fernTestValuePriority *bool
		obj.SetPriority(fernTestValuePriority)
		assert.Equal(t, fernTestValuePriority, obj.Priority)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitRefineCheckoutQuoteBody(t *testing.T) {
	t.Run("SetQuoteId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RefineCheckoutQuoteBody{}
		var fernTestValueQuoteId string

		// Act
		obj.SetQuoteId(fernTestValueQuoteId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPriority_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RefineCheckoutQuoteBody{}
		var fernTestValuePriority *bool

		// Act
		obj.SetPriority(fernTestValuePriority)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCheckoutQuote(t *testing.T) {
	t.Run("SetId", func(t *testing.T) {
		obj := &CheckoutQuote{}
		var fernTestValueId string
		obj.SetId(fernTestValueId)
		assert.Equal(t, fernTestValueId, obj.Id)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetParentId", func(t *testing.T) {
		obj := &CheckoutQuote{}
		var fernTestValueParentId *string
		obj.SetParentId(fernTestValueParentId)
		assert.Equal(t, fernTestValueParentId, obj.ParentId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &CheckoutQuote{}
		var fernTestValueCreatedAt time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExpiresAt", func(t *testing.T) {
		obj := &CheckoutQuote{}
		var fernTestValueExpiresAt time.Time
		obj.SetExpiresAt(fernTestValueExpiresAt)
		assert.Equal(t, fernTestValueExpiresAt, obj.ExpiresAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetModality", func(t *testing.T) {
		obj := &CheckoutQuote{}
		var fernTestValueModality LabTestCollectionMethod
		obj.SetModality(fernTestValueModality)
		assert.Equal(t, fernTestValueModality, obj.Modality)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPriority", func(t *testing.T) {
		obj := &CheckoutQuote{}
		var fernTestValuePriority bool
		obj.SetPriority(fernTestValuePriority)
		assert.Equal(t, fernTestValuePriority, obj.Priority)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUsState", func(t *testing.T) {
		obj := &CheckoutQuote{}
		var fernTestValueUsState string
		obj.SetUsState(fernTestValueUsState)
		assert.Equal(t, fernTestValueUsState, obj.UsState)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOrderSet", func(t *testing.T) {
		obj := &CheckoutQuote{}
		var fernTestValueOrderSet *OrderSetRequest
		obj.SetOrderSet(fernTestValueOrderSet)
		assert.Equal(t, fernTestValueOrderSet, obj.OrderSet)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWalkInCollectionNetworks", func(t *testing.T) {
		obj := &CheckoutQuote{}
		var fernTestValueWalkInCollectionNetworks []WalkInCollectionNetworkSlug
		obj.SetWalkInCollectionNetworks(fernTestValueWalkInCollectionNetworks)
		assert.Equal(t, fernTestValueWalkInCollectionNetworks, obj.WalkInCollectionNetworks)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLineItems", func(t *testing.T) {
		obj := &CheckoutQuote{}
		var fernTestValueLineItems []*CheckoutQuoteLineItem
		obj.SetLineItems(fernTestValueLineItems)
		assert.Equal(t, fernTestValueLineItems, obj.LineItems)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCheckoutQuote(t *testing.T) {
	t.Run("GetId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var expected string
		obj.Id = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetId(), "getter should return the property value")
	})

	t.Run("GetId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuote
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetId() // Should return zero value
	})

	t.Run("GetParentId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var expected *string
		obj.ParentId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetParentId(), "getter should return the property value")
	})

	t.Run("GetParentId_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		obj.ParentId = nil

		// Act & Assert
		assert.Nil(t, obj.GetParentId(), "getter should return nil when property is nil")
	})

	t.Run("GetParentId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuote
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetParentId() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var expected time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuote
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetExpiresAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var expected time.Time
		obj.ExpiresAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExpiresAt(), "getter should return the property value")
	})

	t.Run("GetExpiresAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuote
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExpiresAt() // Should return zero value
	})

	t.Run("GetModality", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var expected LabTestCollectionMethod
		obj.Modality = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetModality(), "getter should return the property value")
	})

	t.Run("GetModality_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuote
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetModality() // Should return zero value
	})

	t.Run("GetPriority", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var expected bool
		obj.Priority = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPriority(), "getter should return the property value")
	})

	t.Run("GetPriority_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuote
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPriority() // Should return zero value
	})

	t.Run("GetUsState", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var expected string
		obj.UsState = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUsState(), "getter should return the property value")
	})

	t.Run("GetUsState_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuote
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUsState() // Should return zero value
	})

	t.Run("GetOrderSet", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var expected *OrderSetRequest
		obj.OrderSet = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOrderSet(), "getter should return the property value")
	})

	t.Run("GetOrderSet_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		obj.OrderSet = nil

		// Act & Assert
		assert.Nil(t, obj.GetOrderSet(), "getter should return nil when property is nil")
	})

	t.Run("GetOrderSet_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuote
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOrderSet() // Should return zero value
	})

	t.Run("GetWalkInCollectionNetworks", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var expected []WalkInCollectionNetworkSlug
		obj.WalkInCollectionNetworks = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWalkInCollectionNetworks(), "getter should return the property value")
	})

	t.Run("GetWalkInCollectionNetworks_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		obj.WalkInCollectionNetworks = nil

		// Act & Assert
		assert.Nil(t, obj.GetWalkInCollectionNetworks(), "getter should return nil when property is nil")
	})

	t.Run("GetWalkInCollectionNetworks_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuote
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWalkInCollectionNetworks() // Should return zero value
	})

	t.Run("GetLineItems", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var expected []*CheckoutQuoteLineItem
		obj.LineItems = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLineItems(), "getter should return the property value")
	})

	t.Run("GetLineItems_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		obj.LineItems = nil

		// Act & Assert
		assert.Nil(t, obj.GetLineItems(), "getter should return nil when property is nil")
	})

	t.Run("GetLineItems_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuote
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLineItems() // Should return zero value
	})

}

func TestSettersMarkExplicitCheckoutQuote(t *testing.T) {
	t.Run("SetId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var fernTestValueId string

		// Act
		obj.SetId(fernTestValueId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetParentId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var fernTestValueParentId *string

		// Act
		obj.SetParentId(fernTestValueParentId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var fernTestValueCreatedAt time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExpiresAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var fernTestValueExpiresAt time.Time

		// Act
		obj.SetExpiresAt(fernTestValueExpiresAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetModality_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var fernTestValueModality LabTestCollectionMethod

		// Act
		obj.SetModality(fernTestValueModality)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPriority_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var fernTestValuePriority bool

		// Act
		obj.SetPriority(fernTestValuePriority)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUsState_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var fernTestValueUsState string

		// Act
		obj.SetUsState(fernTestValueUsState)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOrderSet_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var fernTestValueOrderSet *OrderSetRequest

		// Act
		obj.SetOrderSet(fernTestValueOrderSet)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWalkInCollectionNetworks_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var fernTestValueWalkInCollectionNetworks []WalkInCollectionNetworkSlug

		// Act
		obj.SetWalkInCollectionNetworks(fernTestValueWalkInCollectionNetworks)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLineItems_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}
		var fernTestValueLineItems []*CheckoutQuoteLineItem

		// Act
		obj.SetLineItems(fernTestValueLineItems)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCheckoutQuoteLineItem(t *testing.T) {
	t.Run("SetCode", func(t *testing.T) {
		obj := &CheckoutQuoteLineItem{}
		var fernTestValueCode CheckoutQuoteLineItemCode
		obj.SetCode(fernTestValueCode)
		assert.Equal(t, fernTestValueCode, obj.Code)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAmountMinor", func(t *testing.T) {
		obj := &CheckoutQuoteLineItem{}
		var fernTestValueAmountMinor int
		obj.SetAmountMinor(fernTestValueAmountMinor)
		assert.Equal(t, fernTestValueAmountMinor, obj.AmountMinor)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCheckoutQuoteLineItem(t *testing.T) {
	t.Run("GetCode", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuoteLineItem{}
		var expected CheckoutQuoteLineItemCode
		obj.Code = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCode(), "getter should return the property value")
	})

	t.Run("GetCode_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuoteLineItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCode() // Should return zero value
	})

	t.Run("GetAmountMinor", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuoteLineItem{}
		var expected int
		obj.AmountMinor = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAmountMinor(), "getter should return the property value")
	})

	t.Run("GetAmountMinor_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuoteLineItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAmountMinor() // Should return zero value
	})

}

func TestSettersMarkExplicitCheckoutQuoteLineItem(t *testing.T) {
	t.Run("SetCode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuoteLineItem{}
		var fernTestValueCode CheckoutQuoteLineItemCode

		// Act
		obj.SetCode(fernTestValueCode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAmountMinor_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuoteLineItem{}
		var fernTestValueAmountMinor int

		// Act
		obj.SetAmountMinor(fernTestValueAmountMinor)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCheckoutSession(t *testing.T) {
	t.Run("SetCheckoutId", func(t *testing.T) {
		obj := &CheckoutSession{}
		var fernTestValueCheckoutId string
		obj.SetCheckoutId(fernTestValueCheckoutId)
		assert.Equal(t, fernTestValueCheckoutId, obj.CheckoutId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &CheckoutSession{}
		var fernTestValueStatus CheckoutSessionStatus
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPayBefore", func(t *testing.T) {
		obj := &CheckoutSession{}
		var fernTestValuePayBefore time.Time
		obj.SetPayBefore(fernTestValuePayBefore)
		assert.Equal(t, fernTestValuePayBefore, obj.PayBefore)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPaymentResourceId", func(t *testing.T) {
		obj := &CheckoutSession{}
		var fernTestValuePaymentResourceId *string
		obj.SetPaymentResourceId(fernTestValuePaymentResourceId)
		assert.Equal(t, fernTestValuePaymentResourceId, obj.PaymentResourceId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOrderId", func(t *testing.T) {
		obj := &CheckoutSession{}
		var fernTestValueOrderId *string
		obj.SetOrderId(fernTestValueOrderId)
		assert.Equal(t, fernTestValueOrderId, obj.OrderId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOrderTransactionId", func(t *testing.T) {
		obj := &CheckoutSession{}
		var fernTestValueOrderTransactionId *string
		obj.SetOrderTransactionId(fernTestValueOrderTransactionId)
		assert.Equal(t, fernTestValueOrderTransactionId, obj.OrderTransactionId)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCheckoutSession(t *testing.T) {
	t.Run("GetCheckoutId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}
		var expected string
		obj.CheckoutId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCheckoutId(), "getter should return the property value")
	})

	t.Run("GetCheckoutId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutSession
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCheckoutId() // Should return zero value
	})

	t.Run("GetStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}
		var expected CheckoutSessionStatus
		obj.Status = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatus(), "getter should return the property value")
	})

	t.Run("GetStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutSession
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatus() // Should return zero value
	})

	t.Run("GetPayBefore", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}
		var expected time.Time
		obj.PayBefore = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPayBefore(), "getter should return the property value")
	})

	t.Run("GetPayBefore_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutSession
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPayBefore() // Should return zero value
	})

	t.Run("GetPaymentResourceId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}
		var expected *string
		obj.PaymentResourceId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPaymentResourceId(), "getter should return the property value")
	})

	t.Run("GetPaymentResourceId_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}
		obj.PaymentResourceId = nil

		// Act & Assert
		assert.Nil(t, obj.GetPaymentResourceId(), "getter should return nil when property is nil")
	})

	t.Run("GetPaymentResourceId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutSession
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPaymentResourceId() // Should return zero value
	})

	t.Run("GetOrderId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}
		var expected *string
		obj.OrderId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOrderId(), "getter should return the property value")
	})

	t.Run("GetOrderId_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}
		obj.OrderId = nil

		// Act & Assert
		assert.Nil(t, obj.GetOrderId(), "getter should return nil when property is nil")
	})

	t.Run("GetOrderId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutSession
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOrderId() // Should return zero value
	})

	t.Run("GetOrderTransactionId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}
		var expected *string
		obj.OrderTransactionId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOrderTransactionId(), "getter should return the property value")
	})

	t.Run("GetOrderTransactionId_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}
		obj.OrderTransactionId = nil

		// Act & Assert
		assert.Nil(t, obj.GetOrderTransactionId(), "getter should return nil when property is nil")
	})

	t.Run("GetOrderTransactionId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutSession
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOrderTransactionId() // Should return zero value
	})

}

func TestSettersMarkExplicitCheckoutSession(t *testing.T) {
	t.Run("SetCheckoutId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}
		var fernTestValueCheckoutId string

		// Act
		obj.SetCheckoutId(fernTestValueCheckoutId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}
		var fernTestValueStatus CheckoutSessionStatus

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPayBefore_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}
		var fernTestValuePayBefore time.Time

		// Act
		obj.SetPayBefore(fernTestValuePayBefore)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPaymentResourceId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}
		var fernTestValuePaymentResourceId *string

		// Act
		obj.SetPaymentResourceId(fernTestValuePaymentResourceId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOrderId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}
		var fernTestValueOrderId *string

		// Act
		obj.SetOrderId(fernTestValueOrderId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOrderTransactionId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}
		var fernTestValueOrderTransactionId *string

		// Act
		obj.SetOrderTransactionId(fernTestValueOrderTransactionId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingCheckoutQuote(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuote{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CheckoutQuote
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CheckoutQuote
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CheckoutQuote
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingCheckoutQuoteLineItem(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutQuoteLineItem{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CheckoutQuoteLineItem
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CheckoutQuoteLineItem
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

}

func TestJSONMarshalingCheckoutSession(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CheckoutSession{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CheckoutSession
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CheckoutSession
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CheckoutSession
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringCheckoutQuote(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CheckoutQuote{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuote
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCheckoutQuoteLineItem(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CheckoutQuoteLineItem{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuoteLineItem
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCheckoutSession(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CheckoutSession{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutSession
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumCheckoutQuoteLineItemCode(t *testing.T) {
	t.Run("NewFromString_lab_test_fee", func(t *testing.T) {
		t.Parallel()
		val, err := NewCheckoutQuoteLineItemCodeFromString("lab_test_fee")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CheckoutQuoteLineItemCode("lab_test_fee"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_draw_fee", func(t *testing.T) {
		t.Parallel()
		val, err := NewCheckoutQuoteLineItemCodeFromString("draw_fee")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CheckoutQuoteLineItemCode("draw_fee"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewCheckoutQuoteLineItemCodeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewCheckoutQuoteLineItemCodeFromString("lab_test_fee")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumCheckoutSessionStatus(t *testing.T) {
	t.Run("NewFromString_unpaid", func(t *testing.T) {
		t.Parallel()
		val, err := NewCheckoutSessionStatusFromString("unpaid")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CheckoutSessionStatus("unpaid"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_paid", func(t *testing.T) {
		t.Parallel()
		val, err := NewCheckoutSessionStatusFromString("paid")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CheckoutSessionStatus("paid"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_expired", func(t *testing.T) {
		t.Parallel()
		val, err := NewCheckoutSessionStatusFromString("expired")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CheckoutSessionStatus("expired"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cancelled", func(t *testing.T) {
		t.Parallel()
		val, err := NewCheckoutSessionStatusFromString("cancelled")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CheckoutSessionStatus("cancelled"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewCheckoutSessionStatusFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewCheckoutSessionStatusFromString("unpaid")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumWalkInCollectionNetworkSlug(t *testing.T) {
	t.Run("NewFromString_quest", func(t *testing.T) {
		t.Parallel()
		val, err := NewWalkInCollectionNetworkSlugFromString("quest")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WalkInCollectionNetworkSlug("quest"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_sonora_quest", func(t *testing.T) {
		t.Parallel()
		val, err := NewWalkInCollectionNetworkSlugFromString("sonora_quest")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WalkInCollectionNetworkSlug("sonora_quest"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_labcorp", func(t *testing.T) {
		t.Parallel()
		val, err := NewWalkInCollectionNetworkSlugFromString("labcorp")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WalkInCollectionNetworkSlug("labcorp"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_bioreference", func(t *testing.T) {
		t.Parallel()
		val, err := NewWalkInCollectionNetworkSlugFromString("bioreference")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WalkInCollectionNetworkSlug("bioreference"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewWalkInCollectionNetworkSlugFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewWalkInCollectionNetworkSlugFromString("quest")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesCheckoutQuote(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CheckoutQuote{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuote
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCheckoutQuoteLineItem(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CheckoutQuoteLineItem{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutQuoteLineItem
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCheckoutSession(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CheckoutSession{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CheckoutSession
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
