// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersGetElectrocardiogramRequest(t *testing.T) {
	t.Run("SetUserId", func(t *testing.T) {
		obj := &GetElectrocardiogramRequest{}
		var fernTestValueUserId string
		obj.SetUserId(fernTestValueUserId)
		assert.Equal(t, fernTestValueUserId, obj.UserId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStartDate", func(t *testing.T) {
		obj := &GetElectrocardiogramRequest{}
		var fernTestValueStartDate string
		obj.SetStartDate(fernTestValueStartDate)
		assert.Equal(t, fernTestValueStartDate, obj.StartDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndDate", func(t *testing.T) {
		obj := &GetElectrocardiogramRequest{}
		var fernTestValueEndDate *string
		obj.SetEndDate(fernTestValueEndDate)
		assert.Equal(t, fernTestValueEndDate, obj.EndDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProvider", func(t *testing.T) {
		obj := &GetElectrocardiogramRequest{}
		var fernTestValueProvider *string
		obj.SetProvider(fernTestValueProvider)
		assert.Equal(t, fernTestValueProvider, obj.Provider)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetElectrocardiogramRequest(t *testing.T) {
	t.Run("SetUserId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetElectrocardiogramRequest{}
		var fernTestValueUserId string

		// Act
		obj.SetUserId(fernTestValueUserId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStartDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetElectrocardiogramRequest{}
		var fernTestValueStartDate string

		// Act
		obj.SetStartDate(fernTestValueStartDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetElectrocardiogramRequest{}
		var fernTestValueEndDate *string

		// Act
		obj.SetEndDate(fernTestValueEndDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProvider_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetElectrocardiogramRequest{}
		var fernTestValueProvider *string

		// Act
		obj.SetProvider(fernTestValueProvider)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersClientFacingElectrocardiogram(t *testing.T) {
	t.Run("SetId", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueId string
		obj.SetId(fernTestValueId)
		assert.Equal(t, fernTestValueId, obj.Id)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSessionStart", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSessionStart time.Time
		obj.SetSessionStart(fernTestValueSessionStart)
		assert.Equal(t, fernTestValueSessionStart, obj.SessionStart)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSessionEnd", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSessionEnd time.Time
		obj.SetSessionEnd(fernTestValueSessionEnd)
		assert.Equal(t, fernTestValueSessionEnd, obj.SessionEnd)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVoltageSampleCount", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueVoltageSampleCount int
		obj.SetVoltageSampleCount(fernTestValueVoltageSampleCount)
		assert.Equal(t, fernTestValueVoltageSampleCount, obj.VoltageSampleCount)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHeartRateMean", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueHeartRateMean *int
		obj.SetHeartRateMean(fernTestValueHeartRateMean)
		assert.Equal(t, fernTestValueHeartRateMean, obj.HeartRateMean)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSamplingFrequencyHz", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSamplingFrequencyHz *float64
		obj.SetSamplingFrequencyHz(fernTestValueSamplingFrequencyHz)
		assert.Equal(t, fernTestValueSamplingFrequencyHz, obj.SamplingFrequencyHz)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetClassification", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueClassification *ClientFacingElectrocardiogramClassification
		obj.SetClassification(fernTestValueClassification)
		assert.Equal(t, fernTestValueClassification, obj.Classification)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetInconclusiveCause", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueInconclusiveCause *ClientFacingElectrocardiogramInconclusiveCause
		obj.SetInconclusiveCause(fernTestValueInconclusiveCause)
		assert.Equal(t, fernTestValueInconclusiveCause, obj.InconclusiveCause)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAlgorithmVersion", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueAlgorithmVersion *string
		obj.SetAlgorithmVersion(fernTestValueAlgorithmVersion)
		assert.Equal(t, fernTestValueAlgorithmVersion, obj.AlgorithmVersion)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTimeZone", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueTimeZone *string
		obj.SetTimeZone(fernTestValueTimeZone)
		assert.Equal(t, fernTestValueTimeZone, obj.TimeZone)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSourceProvider", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSourceProvider *ClientFacingElectrocardiogramSourceProvider
		obj.SetSourceProvider(fernTestValueSourceProvider)
		assert.Equal(t, fernTestValueSourceProvider, obj.SourceProvider)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSourceType", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSourceType ClientFacingElectrocardiogramSourceType
		obj.SetSourceType(fernTestValueSourceType)
		assert.Equal(t, fernTestValueSourceType, obj.SourceType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSourceAppId", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSourceAppId *string
		obj.SetSourceAppId(fernTestValueSourceAppId)
		assert.Equal(t, fernTestValueSourceAppId, obj.SourceAppId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSourceDeviceModel", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSourceDeviceModel *string
		obj.SetSourceDeviceModel(fernTestValueSourceDeviceModel)
		assert.Equal(t, fernTestValueSourceDeviceModel, obj.SourceDeviceModel)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSourceDeviceId", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSourceDeviceId *string
		obj.SetSourceDeviceId(fernTestValueSourceDeviceId)
		assert.Equal(t, fernTestValueSourceDeviceId, obj.SourceDeviceId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueCreatedAt time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUpdatedAt", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueUpdatedAt time.Time
		obj.SetUpdatedAt(fernTestValueUpdatedAt)
		assert.Equal(t, fernTestValueUpdatedAt, obj.UpdatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUserId", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueUserId string
		obj.SetUserId(fernTestValueUserId)
		assert.Equal(t, fernTestValueUserId, obj.UserId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSource", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSource *ClientFacingSource
		obj.SetSource(fernTestValueSource)
		assert.Equal(t, fernTestValueSource, obj.Source)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersClientFacingElectrocardiogram(t *testing.T) {
	t.Run("GetId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected string
		obj.Id = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetId(), "getter should return the property value")
	})

	t.Run("GetId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetId() // Should return zero value
	})

	t.Run("GetSessionStart", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected time.Time
		obj.SessionStart = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSessionStart(), "getter should return the property value")
	})

	t.Run("GetSessionStart_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSessionStart() // Should return zero value
	})

	t.Run("GetSessionEnd", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected time.Time
		obj.SessionEnd = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSessionEnd(), "getter should return the property value")
	})

	t.Run("GetSessionEnd_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSessionEnd() // Should return zero value
	})

	t.Run("GetVoltageSampleCount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected int
		obj.VoltageSampleCount = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVoltageSampleCount(), "getter should return the property value")
	})

	t.Run("GetVoltageSampleCount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVoltageSampleCount() // Should return zero value
	})

	t.Run("GetHeartRateMean", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected *int
		obj.HeartRateMean = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHeartRateMean(), "getter should return the property value")
	})

	t.Run("GetHeartRateMean_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		obj.HeartRateMean = nil

		// Act & Assert
		assert.Nil(t, obj.GetHeartRateMean(), "getter should return nil when property is nil")
	})

	t.Run("GetHeartRateMean_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHeartRateMean() // Should return zero value
	})

	t.Run("GetSamplingFrequencyHz", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected *float64
		obj.SamplingFrequencyHz = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSamplingFrequencyHz(), "getter should return the property value")
	})

	t.Run("GetSamplingFrequencyHz_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		obj.SamplingFrequencyHz = nil

		// Act & Assert
		assert.Nil(t, obj.GetSamplingFrequencyHz(), "getter should return nil when property is nil")
	})

	t.Run("GetSamplingFrequencyHz_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSamplingFrequencyHz() // Should return zero value
	})

	t.Run("GetClassification", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected *ClientFacingElectrocardiogramClassification
		obj.Classification = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetClassification(), "getter should return the property value")
	})

	t.Run("GetClassification_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		obj.Classification = nil

		// Act & Assert
		assert.Nil(t, obj.GetClassification(), "getter should return nil when property is nil")
	})

	t.Run("GetClassification_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetClassification() // Should return zero value
	})

	t.Run("GetInconclusiveCause", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected *ClientFacingElectrocardiogramInconclusiveCause
		obj.InconclusiveCause = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetInconclusiveCause(), "getter should return the property value")
	})

	t.Run("GetInconclusiveCause_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		obj.InconclusiveCause = nil

		// Act & Assert
		assert.Nil(t, obj.GetInconclusiveCause(), "getter should return nil when property is nil")
	})

	t.Run("GetInconclusiveCause_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetInconclusiveCause() // Should return zero value
	})

	t.Run("GetAlgorithmVersion", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected *string
		obj.AlgorithmVersion = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAlgorithmVersion(), "getter should return the property value")
	})

	t.Run("GetAlgorithmVersion_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		obj.AlgorithmVersion = nil

		// Act & Assert
		assert.Nil(t, obj.GetAlgorithmVersion(), "getter should return nil when property is nil")
	})

	t.Run("GetAlgorithmVersion_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAlgorithmVersion() // Should return zero value
	})

	t.Run("GetTimeZone", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected *string
		obj.TimeZone = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTimeZone(), "getter should return the property value")
	})

	t.Run("GetTimeZone_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		obj.TimeZone = nil

		// Act & Assert
		assert.Nil(t, obj.GetTimeZone(), "getter should return nil when property is nil")
	})

	t.Run("GetTimeZone_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTimeZone() // Should return zero value
	})

	t.Run("GetSourceProvider", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected *ClientFacingElectrocardiogramSourceProvider
		obj.SourceProvider = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSourceProvider(), "getter should return the property value")
	})

	t.Run("GetSourceProvider_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		obj.SourceProvider = nil

		// Act & Assert
		assert.Nil(t, obj.GetSourceProvider(), "getter should return nil when property is nil")
	})

	t.Run("GetSourceProvider_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSourceProvider() // Should return zero value
	})

	t.Run("GetSourceType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected ClientFacingElectrocardiogramSourceType
		obj.SourceType = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSourceType(), "getter should return the property value")
	})

	t.Run("GetSourceType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSourceType() // Should return zero value
	})

	t.Run("GetSourceAppId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected *string
		obj.SourceAppId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSourceAppId(), "getter should return the property value")
	})

	t.Run("GetSourceAppId_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		obj.SourceAppId = nil

		// Act & Assert
		assert.Nil(t, obj.GetSourceAppId(), "getter should return nil when property is nil")
	})

	t.Run("GetSourceAppId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSourceAppId() // Should return zero value
	})

	t.Run("GetSourceDeviceModel", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected *string
		obj.SourceDeviceModel = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSourceDeviceModel(), "getter should return the property value")
	})

	t.Run("GetSourceDeviceModel_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		obj.SourceDeviceModel = nil

		// Act & Assert
		assert.Nil(t, obj.GetSourceDeviceModel(), "getter should return nil when property is nil")
	})

	t.Run("GetSourceDeviceModel_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSourceDeviceModel() // Should return zero value
	})

	t.Run("GetSourceDeviceId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected *string
		obj.SourceDeviceId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSourceDeviceId(), "getter should return the property value")
	})

	t.Run("GetSourceDeviceId_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		obj.SourceDeviceId = nil

		// Act & Assert
		assert.Nil(t, obj.GetSourceDeviceId(), "getter should return nil when property is nil")
	})

	t.Run("GetSourceDeviceId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSourceDeviceId() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetUpdatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected time.Time
		obj.UpdatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUpdatedAt(), "getter should return the property value")
	})

	t.Run("GetUpdatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUpdatedAt() // Should return zero value
	})

	t.Run("GetUserId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected string
		obj.UserId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUserId(), "getter should return the property value")
	})

	t.Run("GetUserId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUserId() // Should return zero value
	})

	t.Run("GetSource", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var expected *ClientFacingSource
		obj.Source = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSource(), "getter should return the property value")
	})

	t.Run("GetSource_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		obj.Source = nil

		// Act & Assert
		assert.Nil(t, obj.GetSource(), "getter should return nil when property is nil")
	})

	t.Run("GetSource_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSource() // Should return zero value
	})

}

func TestSettersMarkExplicitClientFacingElectrocardiogram(t *testing.T) {
	t.Run("SetId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueId string

		// Act
		obj.SetId(fernTestValueId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSessionStart_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSessionStart time.Time

		// Act
		obj.SetSessionStart(fernTestValueSessionStart)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSessionEnd_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSessionEnd time.Time

		// Act
		obj.SetSessionEnd(fernTestValueSessionEnd)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVoltageSampleCount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueVoltageSampleCount int

		// Act
		obj.SetVoltageSampleCount(fernTestValueVoltageSampleCount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHeartRateMean_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueHeartRateMean *int

		// Act
		obj.SetHeartRateMean(fernTestValueHeartRateMean)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSamplingFrequencyHz_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSamplingFrequencyHz *float64

		// Act
		obj.SetSamplingFrequencyHz(fernTestValueSamplingFrequencyHz)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetClassification_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueClassification *ClientFacingElectrocardiogramClassification

		// Act
		obj.SetClassification(fernTestValueClassification)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetInconclusiveCause_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueInconclusiveCause *ClientFacingElectrocardiogramInconclusiveCause

		// Act
		obj.SetInconclusiveCause(fernTestValueInconclusiveCause)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAlgorithmVersion_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueAlgorithmVersion *string

		// Act
		obj.SetAlgorithmVersion(fernTestValueAlgorithmVersion)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTimeZone_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueTimeZone *string

		// Act
		obj.SetTimeZone(fernTestValueTimeZone)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSourceProvider_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSourceProvider *ClientFacingElectrocardiogramSourceProvider

		// Act
		obj.SetSourceProvider(fernTestValueSourceProvider)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSourceType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSourceType ClientFacingElectrocardiogramSourceType

		// Act
		obj.SetSourceType(fernTestValueSourceType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSourceAppId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSourceAppId *string

		// Act
		obj.SetSourceAppId(fernTestValueSourceAppId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSourceDeviceModel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSourceDeviceModel *string

		// Act
		obj.SetSourceDeviceModel(fernTestValueSourceDeviceModel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSourceDeviceId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSourceDeviceId *string

		// Act
		obj.SetSourceDeviceId(fernTestValueSourceDeviceId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueCreatedAt time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUpdatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueUpdatedAt time.Time

		// Act
		obj.SetUpdatedAt(fernTestValueUpdatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUserId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueUserId string

		// Act
		obj.SetUserId(fernTestValueUserId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSource_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}
		var fernTestValueSource *ClientFacingSource

		// Act
		obj.SetSource(fernTestValueSource)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersClientFacingElectrocardiogramResponse(t *testing.T) {
	t.Run("SetElectrocardiogram", func(t *testing.T) {
		obj := &ClientFacingElectrocardiogramResponse{}
		var fernTestValueElectrocardiogram []*ClientFacingElectrocardiogram
		obj.SetElectrocardiogram(fernTestValueElectrocardiogram)
		assert.Equal(t, fernTestValueElectrocardiogram, obj.Electrocardiogram)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersClientFacingElectrocardiogramResponse(t *testing.T) {
	t.Run("GetElectrocardiogram", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogramResponse{}
		var expected []*ClientFacingElectrocardiogram
		obj.Electrocardiogram = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetElectrocardiogram(), "getter should return the property value")
	})

	t.Run("GetElectrocardiogram_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogramResponse{}
		obj.Electrocardiogram = nil

		// Act & Assert
		assert.Nil(t, obj.GetElectrocardiogram(), "getter should return nil when property is nil")
	})

	t.Run("GetElectrocardiogram_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogramResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetElectrocardiogram() // Should return zero value
	})

}

func TestSettersMarkExplicitClientFacingElectrocardiogramResponse(t *testing.T) {
	t.Run("SetElectrocardiogram_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogramResponse{}
		var fernTestValueElectrocardiogram []*ClientFacingElectrocardiogram

		// Act
		obj.SetElectrocardiogram(fernTestValueElectrocardiogram)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestGettersClientFacingElectrocardiogramSourceProvider(t *testing.T) {
	t.Run("GetProviders", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogramSourceProvider{}
		var expected Providers
		obj.Providers = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProviders(), "getter should return the property value")
	})

	t.Run("GetProviders_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogramSourceProvider
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProviders() // Should return zero value
	})

	t.Run("GetLabs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogramSourceProvider{}
		var expected Labs
		obj.Labs = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLabs(), "getter should return the property value")
	})

	t.Run("GetLabs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogramSourceProvider
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLabs() // Should return zero value
	})

}

func TestJSONMarshalingClientFacingElectrocardiogram(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogram{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ClientFacingElectrocardiogram
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ClientFacingElectrocardiogram
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ClientFacingElectrocardiogram
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingClientFacingElectrocardiogramResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingElectrocardiogramResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ClientFacingElectrocardiogramResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ClientFacingElectrocardiogramResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ClientFacingElectrocardiogramResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringClientFacingElectrocardiogram(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ClientFacingElectrocardiogram{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringClientFacingElectrocardiogramResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ClientFacingElectrocardiogramResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogramResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumClientFacingElectrocardiogramClassification(t *testing.T) {
	t.Run("NewFromString_sinus_rhythm", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramClassificationFromString("sinus_rhythm")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramClassification("sinus_rhythm"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_atrial_fibrillation", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramClassificationFromString("atrial_fibrillation")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramClassification("atrial_fibrillation"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_inconclusive", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramClassificationFromString("inconclusive")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramClassification("inconclusive"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewClientFacingElectrocardiogramClassificationFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewClientFacingElectrocardiogramClassificationFromString("sinus_rhythm")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumClientFacingElectrocardiogramInconclusiveCause(t *testing.T) {
	t.Run("NewFromString_high_heart_rate", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramInconclusiveCauseFromString("high_heart_rate")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramInconclusiveCause("high_heart_rate"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_low_heart_rate", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramInconclusiveCauseFromString("low_heart_rate")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramInconclusiveCause("low_heart_rate"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_poor_reading", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramInconclusiveCauseFromString("poor_reading")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramInconclusiveCause("poor_reading"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewClientFacingElectrocardiogramInconclusiveCauseFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewClientFacingElectrocardiogramInconclusiveCauseFromString("high_heart_rate")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumClientFacingElectrocardiogramSourceType(t *testing.T) {
	t.Run("NewFromString_unknown", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("unknown")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("unknown"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_phone", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("phone")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("phone"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_watch", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("watch")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("watch"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_app", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("app")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("app"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_multiple_sources", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("multiple_sources")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("multiple_sources"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_fingerprick", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("fingerprick")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("fingerprick"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cuff", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("cuff")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("cuff"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_manual_scan", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("manual_scan")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("manual_scan"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_automatic", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("automatic")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("automatic"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_insulin_pump", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("insulin_pump")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("insulin_pump"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_scale", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("scale")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("scale"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_chest_strap", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("chest_strap")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("chest_strap"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_ring", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("ring")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("ring"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_lab", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("lab")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("lab"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_exercise_machine", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("exercise_machine")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("exercise_machine"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_earphone", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("earphone")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingElectrocardiogramSourceType("earphone"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewClientFacingElectrocardiogramSourceTypeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewClientFacingElectrocardiogramSourceTypeFromString("unknown")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesClientFacingElectrocardiogram(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ClientFacingElectrocardiogram{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogram
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesClientFacingElectrocardiogramResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ClientFacingElectrocardiogramResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingElectrocardiogramResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
