// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersGetSleepCycleRequest(t *testing.T) {
	t.Run("SetUserId", func(t *testing.T) {
		obj := &GetSleepCycleRequest{}
		var fernTestValueUserId string
		obj.SetUserId(fernTestValueUserId)
		assert.Equal(t, fernTestValueUserId, obj.UserId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStartDate", func(t *testing.T) {
		obj := &GetSleepCycleRequest{}
		var fernTestValueStartDate string
		obj.SetStartDate(fernTestValueStartDate)
		assert.Equal(t, fernTestValueStartDate, obj.StartDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndDate", func(t *testing.T) {
		obj := &GetSleepCycleRequest{}
		var fernTestValueEndDate *string
		obj.SetEndDate(fernTestValueEndDate)
		assert.Equal(t, fernTestValueEndDate, obj.EndDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProvider", func(t *testing.T) {
		obj := &GetSleepCycleRequest{}
		var fernTestValueProvider *string
		obj.SetProvider(fernTestValueProvider)
		assert.Equal(t, fernTestValueProvider, obj.Provider)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetSleepCycleRequest(t *testing.T) {
	t.Run("SetUserId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetSleepCycleRequest{}
		var fernTestValueUserId string

		// Act
		obj.SetUserId(fernTestValueUserId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStartDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetSleepCycleRequest{}
		var fernTestValueStartDate string

		// Act
		obj.SetStartDate(fernTestValueStartDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetSleepCycleRequest{}
		var fernTestValueEndDate *string

		// Act
		obj.SetEndDate(fernTestValueEndDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProvider_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetSleepCycleRequest{}
		var fernTestValueProvider *string

		// Act
		obj.SetProvider(fernTestValueProvider)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersClientFacingSleepCycle(t *testing.T) {
	t.Run("SetId", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueId string
		obj.SetId(fernTestValueId)
		assert.Equal(t, fernTestValueId, obj.Id)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSleepId", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSleepId string
		obj.SetSleepId(fernTestValueSleepId)
		assert.Equal(t, fernTestValueSleepId, obj.SleepId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSessionStart", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSessionStart time.Time
		obj.SetSessionStart(fernTestValueSessionStart)
		assert.Equal(t, fernTestValueSessionStart, obj.SessionStart)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSessionEnd", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSessionEnd time.Time
		obj.SetSessionEnd(fernTestValueSessionEnd)
		assert.Equal(t, fernTestValueSessionEnd, obj.SessionEnd)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStageStartOffsetSecond", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueStageStartOffsetSecond []int
		obj.SetStageStartOffsetSecond(fernTestValueStageStartOffsetSecond)
		assert.Equal(t, fernTestValueStageStartOffsetSecond, obj.StageStartOffsetSecond)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStageEndOffsetSecond", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueStageEndOffsetSecond []int
		obj.SetStageEndOffsetSecond(fernTestValueStageEndOffsetSecond)
		assert.Equal(t, fernTestValueStageEndOffsetSecond, obj.StageEndOffsetSecond)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStageType", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueStageType []VitalSleepStage
		obj.SetStageType(fernTestValueStageType)
		assert.Equal(t, fernTestValueStageType, obj.StageType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTimeZone", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueTimeZone *string
		obj.SetTimeZone(fernTestValueTimeZone)
		assert.Equal(t, fernTestValueTimeZone, obj.TimeZone)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSourceProvider", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSourceProvider *ClientFacingSleepCycleSourceProvider
		obj.SetSourceProvider(fernTestValueSourceProvider)
		assert.Equal(t, fernTestValueSourceProvider, obj.SourceProvider)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSourceType", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSourceType ClientFacingSleepCycleSourceType
		obj.SetSourceType(fernTestValueSourceType)
		assert.Equal(t, fernTestValueSourceType, obj.SourceType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSourceAppId", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSourceAppId *string
		obj.SetSourceAppId(fernTestValueSourceAppId)
		assert.Equal(t, fernTestValueSourceAppId, obj.SourceAppId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSourceDeviceId", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSourceDeviceId *string
		obj.SetSourceDeviceId(fernTestValueSourceDeviceId)
		assert.Equal(t, fernTestValueSourceDeviceId, obj.SourceDeviceId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueCreatedAt time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUpdatedAt", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueUpdatedAt time.Time
		obj.SetUpdatedAt(fernTestValueUpdatedAt)
		assert.Equal(t, fernTestValueUpdatedAt, obj.UpdatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUserId", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueUserId string
		obj.SetUserId(fernTestValueUserId)
		assert.Equal(t, fernTestValueUserId, obj.UserId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSource", func(t *testing.T) {
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSource *ClientFacingSource
		obj.SetSource(fernTestValueSource)
		assert.Equal(t, fernTestValueSource, obj.Source)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersClientFacingSleepCycle(t *testing.T) {
	t.Run("GetId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected string
		obj.Id = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetId(), "getter should return the property value")
	})

	t.Run("GetId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetId() // Should return zero value
	})

	t.Run("GetSleepId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected string
		obj.SleepId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSleepId(), "getter should return the property value")
	})

	t.Run("GetSleepId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSleepId() // Should return zero value
	})

	t.Run("GetSessionStart", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected time.Time
		obj.SessionStart = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSessionStart(), "getter should return the property value")
	})

	t.Run("GetSessionStart_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSessionStart() // Should return zero value
	})

	t.Run("GetSessionEnd", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected time.Time
		obj.SessionEnd = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSessionEnd(), "getter should return the property value")
	})

	t.Run("GetSessionEnd_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSessionEnd() // Should return zero value
	})

	t.Run("GetStageStartOffsetSecond", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected []int
		obj.StageStartOffsetSecond = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStageStartOffsetSecond(), "getter should return the property value")
	})

	t.Run("GetStageStartOffsetSecond_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		obj.StageStartOffsetSecond = nil

		// Act & Assert
		assert.Nil(t, obj.GetStageStartOffsetSecond(), "getter should return nil when property is nil")
	})

	t.Run("GetStageStartOffsetSecond_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStageStartOffsetSecond() // Should return zero value
	})

	t.Run("GetStageEndOffsetSecond", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected []int
		obj.StageEndOffsetSecond = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStageEndOffsetSecond(), "getter should return the property value")
	})

	t.Run("GetStageEndOffsetSecond_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		obj.StageEndOffsetSecond = nil

		// Act & Assert
		assert.Nil(t, obj.GetStageEndOffsetSecond(), "getter should return nil when property is nil")
	})

	t.Run("GetStageEndOffsetSecond_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStageEndOffsetSecond() // Should return zero value
	})

	t.Run("GetStageType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected []VitalSleepStage
		obj.StageType = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStageType(), "getter should return the property value")
	})

	t.Run("GetStageType_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		obj.StageType = nil

		// Act & Assert
		assert.Nil(t, obj.GetStageType(), "getter should return nil when property is nil")
	})

	t.Run("GetStageType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStageType() // Should return zero value
	})

	t.Run("GetTimeZone", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected *string
		obj.TimeZone = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTimeZone(), "getter should return the property value")
	})

	t.Run("GetTimeZone_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		obj.TimeZone = nil

		// Act & Assert
		assert.Nil(t, obj.GetTimeZone(), "getter should return nil when property is nil")
	})

	t.Run("GetTimeZone_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTimeZone() // Should return zero value
	})

	t.Run("GetSourceProvider", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected *ClientFacingSleepCycleSourceProvider
		obj.SourceProvider = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSourceProvider(), "getter should return the property value")
	})

	t.Run("GetSourceProvider_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		obj.SourceProvider = nil

		// Act & Assert
		assert.Nil(t, obj.GetSourceProvider(), "getter should return nil when property is nil")
	})

	t.Run("GetSourceProvider_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSourceProvider() // Should return zero value
	})

	t.Run("GetSourceType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected ClientFacingSleepCycleSourceType
		obj.SourceType = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSourceType(), "getter should return the property value")
	})

	t.Run("GetSourceType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSourceType() // Should return zero value
	})

	t.Run("GetSourceAppId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected *string
		obj.SourceAppId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSourceAppId(), "getter should return the property value")
	})

	t.Run("GetSourceAppId_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		obj.SourceAppId = nil

		// Act & Assert
		assert.Nil(t, obj.GetSourceAppId(), "getter should return nil when property is nil")
	})

	t.Run("GetSourceAppId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSourceAppId() // Should return zero value
	})

	t.Run("GetSourceDeviceId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected *string
		obj.SourceDeviceId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSourceDeviceId(), "getter should return the property value")
	})

	t.Run("GetSourceDeviceId_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		obj.SourceDeviceId = nil

		// Act & Assert
		assert.Nil(t, obj.GetSourceDeviceId(), "getter should return nil when property is nil")
	})

	t.Run("GetSourceDeviceId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSourceDeviceId() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetUpdatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected time.Time
		obj.UpdatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUpdatedAt(), "getter should return the property value")
	})

	t.Run("GetUpdatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUpdatedAt() // Should return zero value
	})

	t.Run("GetUserId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected string
		obj.UserId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUserId(), "getter should return the property value")
	})

	t.Run("GetUserId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUserId() // Should return zero value
	})

	t.Run("GetSource", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var expected *ClientFacingSource
		obj.Source = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSource(), "getter should return the property value")
	})

	t.Run("GetSource_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		obj.Source = nil

		// Act & Assert
		assert.Nil(t, obj.GetSource(), "getter should return nil when property is nil")
	})

	t.Run("GetSource_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSource() // Should return zero value
	})

}

func TestSettersMarkExplicitClientFacingSleepCycle(t *testing.T) {
	t.Run("SetId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueId string

		// Act
		obj.SetId(fernTestValueId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSleepId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSleepId string

		// Act
		obj.SetSleepId(fernTestValueSleepId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSessionStart_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSessionStart time.Time

		// Act
		obj.SetSessionStart(fernTestValueSessionStart)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSessionEnd_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSessionEnd time.Time

		// Act
		obj.SetSessionEnd(fernTestValueSessionEnd)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStageStartOffsetSecond_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueStageStartOffsetSecond []int

		// Act
		obj.SetStageStartOffsetSecond(fernTestValueStageStartOffsetSecond)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStageEndOffsetSecond_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueStageEndOffsetSecond []int

		// Act
		obj.SetStageEndOffsetSecond(fernTestValueStageEndOffsetSecond)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStageType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueStageType []VitalSleepStage

		// Act
		obj.SetStageType(fernTestValueStageType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTimeZone_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueTimeZone *string

		// Act
		obj.SetTimeZone(fernTestValueTimeZone)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSourceProvider_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSourceProvider *ClientFacingSleepCycleSourceProvider

		// Act
		obj.SetSourceProvider(fernTestValueSourceProvider)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSourceType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSourceType ClientFacingSleepCycleSourceType

		// Act
		obj.SetSourceType(fernTestValueSourceType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSourceAppId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSourceAppId *string

		// Act
		obj.SetSourceAppId(fernTestValueSourceAppId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSourceDeviceId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSourceDeviceId *string

		// Act
		obj.SetSourceDeviceId(fernTestValueSourceDeviceId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueCreatedAt time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUpdatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueUpdatedAt time.Time

		// Act
		obj.SetUpdatedAt(fernTestValueUpdatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUserId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueUserId string

		// Act
		obj.SetUserId(fernTestValueUserId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSource_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}
		var fernTestValueSource *ClientFacingSource

		// Act
		obj.SetSource(fernTestValueSource)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestGettersClientFacingSleepCycleSourceProvider(t *testing.T) {
	t.Run("GetProviders", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycleSourceProvider{}
		var expected Providers
		obj.Providers = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProviders(), "getter should return the property value")
	})

	t.Run("GetProviders_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycleSourceProvider
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProviders() // Should return zero value
	})

	t.Run("GetLabs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycleSourceProvider{}
		var expected Labs
		obj.Labs = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLabs(), "getter should return the property value")
	})

	t.Run("GetLabs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycleSourceProvider
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLabs() // Should return zero value
	})

}

func TestSettersClientSleepCycleResponse(t *testing.T) {
	t.Run("SetSleepCycle", func(t *testing.T) {
		obj := &ClientSleepCycleResponse{}
		var fernTestValueSleepCycle []*ClientFacingSleepCycle
		obj.SetSleepCycle(fernTestValueSleepCycle)
		assert.Equal(t, fernTestValueSleepCycle, obj.SleepCycle)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersClientSleepCycleResponse(t *testing.T) {
	t.Run("GetSleepCycle", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientSleepCycleResponse{}
		var expected []*ClientFacingSleepCycle
		obj.SleepCycle = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSleepCycle(), "getter should return the property value")
	})

	t.Run("GetSleepCycle_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientSleepCycleResponse{}
		obj.SleepCycle = nil

		// Act & Assert
		assert.Nil(t, obj.GetSleepCycle(), "getter should return nil when property is nil")
	})

	t.Run("GetSleepCycle_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientSleepCycleResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSleepCycle() // Should return zero value
	})

}

func TestSettersMarkExplicitClientSleepCycleResponse(t *testing.T) {
	t.Run("SetSleepCycle_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientSleepCycleResponse{}
		var fernTestValueSleepCycle []*ClientFacingSleepCycle

		// Act
		obj.SetSleepCycle(fernTestValueSleepCycle)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingClientFacingSleepCycle(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientFacingSleepCycle{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ClientFacingSleepCycle
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ClientFacingSleepCycle
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ClientFacingSleepCycle
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingClientSleepCycleResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ClientSleepCycleResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ClientSleepCycleResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ClientSleepCycleResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ClientSleepCycleResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringClientFacingSleepCycle(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ClientFacingSleepCycle{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringClientSleepCycleResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ClientSleepCycleResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientSleepCycleResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumClientFacingSleepCycleSourceType(t *testing.T) {
	t.Run("NewFromString_unknown", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("unknown")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("unknown"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_phone", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("phone")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("phone"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_watch", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("watch")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("watch"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_app", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("app")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("app"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_multiple_sources", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("multiple_sources")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("multiple_sources"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_fingerprick", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("fingerprick")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("fingerprick"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cuff", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("cuff")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("cuff"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_manual_scan", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("manual_scan")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("manual_scan"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_automatic", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("automatic")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("automatic"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_insulin_pump", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("insulin_pump")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("insulin_pump"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_scale", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("scale")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("scale"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_chest_strap", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("chest_strap")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("chest_strap"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_ring", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("ring")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("ring"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_lab", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("lab")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("lab"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_exercise_machine", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("exercise_machine")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("exercise_machine"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_earphone", func(t *testing.T) {
		t.Parallel()
		val, err := NewClientFacingSleepCycleSourceTypeFromString("earphone")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ClientFacingSleepCycleSourceType("earphone"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewClientFacingSleepCycleSourceTypeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewClientFacingSleepCycleSourceTypeFromString("unknown")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesClientFacingSleepCycle(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ClientFacingSleepCycle{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientFacingSleepCycle
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesClientSleepCycleResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ClientSleepCycleResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ClientSleepCycleResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
