// Code generated by Fern. DO NOT EDIT.

package insurance

import (
	context "context"

	junctiongo "github.com/junction-api/junction-go"
	core "github.com/junction-api/junction-go/core"
	internal "github.com/junction-api/junction-go/internal"
	option "github.com/junction-api/junction-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) SearchGetPayorInfo(
	ctx context.Context,
	request *junctiongo.SearchGetPayorInfoInsuranceRequest,
	opts ...option.RequestOption,
) ([]*junctiongo.ClientFacingPayorSearchResponse, error) {
	response, err := c.WithRawResponse.SearchGetPayorInfo(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) SearchPayorInfo(
	ctx context.Context,
	request *junctiongo.PayorSearchRequest,
	opts ...option.RequestOption,
) ([]*junctiongo.ClientFacingPayorSearchResponseDeprecated, error) {
	response, err := c.WithRawResponse.SearchPayorInfo(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) SearchDiagnosis(
	ctx context.Context,
	request *junctiongo.SearchDiagnosisInsuranceRequest,
	opts ...option.RequestOption,
) ([]*junctiongo.ClientFacingDiagnosisInformation, error) {
	response, err := c.WithRawResponse.SearchDiagnosis(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
